"""Agregar telefono a cliente

Revision ID: 03c65de77c74
Revises: 7d5b9e95b6bb
Create Date: 2026-02-17 10:34:09.995645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c65de77c74'
down_revision = '7d5b9e95b6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('email')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
